### ISSUE TITLE
Couple of quick pointers pls

### ISSUE THREAD

**Issue by Roh-codeur** [ReactiveBayes/Rocket.jl#36]
Hi

thanks, this is quite an awesome library. I am using the library Jib.jl to subscribe to data from Interactive brokers. 

quick ques: in Rxpy, there is a method run() to block execution. is there anything similar in Rocket.jl please?

thanks

**Comment by bvdmitri** [comment]
You should use `subscribe!` to start an execution and `unsubscribe!` to stop an execution.

**Comment by oliviermilla** [comment]
@Roh-codeur see https://github.com/oliviermilla/Lucky.jl for a trading framework leveraging Rocket.jl

It's WIP.

Jib.jl isn't integrated yet though. Feel free.
