### ISSUE TITLE
Interval operator with a subscriber function that can take input arguments

### ISSUE THREAD

**Issue by caxelrud** [ReactiveBayes/Rocket.jl#48]
How to use interval operator with a subscriber function that can take input arguments?

For now I am using a function that is using global scope variables, but it is not the best solution.

**Comment by bvdmitri** [comment]
Hey! This is not specific to the `interval`. You can simply implement a callable structure or a specific actor. Read documentation [here](https://docs.julialang.org/en/v1/manual/methods/#Function-like-objects) and [here](https://reactivebayes.github.io/Rocket.jl/stable/getting-started/#Actors). For questions I would advice you to use [Discourse](https://discourse.julialang.org/).
