### ISSUE TITLE
`timer` observable caps number of emissions on high frequency

### ISSUE THREAD

**Issue by wouterwln** [ReactiveBayes/Rocket.jl#50]
This is quite obvious because of processing power, but on my machine it caps at a suspiciously low frequency (+- 900 emissions/sec)
MWE:
```julia
using Rocket

struct CustomKeepActor <: Actor{Int}
    values::Vector{Float64}

    CustomKeepActor() = new(Vector{Float64}())
end

Rocket.on_next!(actor::CustomKeepActor, data::Int) = push!(actor.values, time())

actor = CustomKeepActor()
source = timer(0.1, 0.1)
sink = subscribe!(source, actor)

sleep(1)
# Random interval between two values
println(actor.values[200] - actor.values[199])

# average interval
println(sum(diff(actor.values))/ (length(actor.values)))
```
```
0.0012099742889404297
0.0011341167615997558
```
For me this works at around 900 emissions/sec, even though it should emit 10.000 times per second. I have also seen that even if we do more involved computation on subscription this emission rate does not change.

**Comment by bvdmitri** [comment]
I investigate it a bit. It looks like the built-in julia `Timer` ignores the sub milliseconds interval and basically uses `1ms` as its lowest period (or delay) possible 
```julia
@less Timer(0.0001; interval = 0.0001)
```
has the following line
```
intervalms = ceil(UInt64, interval * 1000)
```
I think its a documentation issue from Julia side. It does not mention that sub-milliseconds intervals or delays are simply ignored. 

P.S. That basically means that #49 had no influence.

**Comment by bauglir** [comment]
Interestingly enough, `sleep` ([which is essentially a wrapper around `Timer`](https://github.com/JuliaLang/julia/blob/d8d384278d6a706e0dc4602bdae1ec1a08908394/base/asyncevent.jl#L265)) [does document that 1ms is the minimum delay possible](https://docs.julialang.org/en/v1/base/parallel/#Base.sleep).

**Comment by bvdmitri** [comment]
https://github.com/JuliaLang/julia/issues/53934
