### ISSUE TITLE
Does rocket.jl support multi-threading and distributed computing?

### ISSUE THREAD

**Issue by Wu-Chenyang** [ReactiveBayes/Rocket.jl#53]
Thanks for your great work on developing Rocket.jl. The documentation is very helpful and is a great introduction to reactive programming. I've read it in its entirety. However, I didn't find any example concerning multi-threading and distributed computing using Rocket.jl. I am new to reactive programming and parallel computing in Julia. It's not clear to me how to combine them using Rocket.jl. Can you provide some examples on this?

**Comment by bvdmitri** [comment]
Hey! Rocket.jl currently doesn't have special support for multi-threading or distributed computing. It's something I've had on my to-do list for a while. Right now, only asynchronous mode is available using the [async](https://reactivebayes.github.io/Rocket.jl/stable/operators/utility/async/) macro. You can find the source code [here](https://github.com/ReactiveBayes/Rocket.jl/blob/main/src/schedulers/async.jl), which might help you implement something similar for multi-threading.

**Comment by Wu-Chenyang** [comment]
Hey! Thanks so much for getting back to me!
It's good to know they're on your to-do list. The async macro sounds like a good starting point and worth a try. 
Also, I’m really excited about the potential future development of concurrent computing features in Rocket.jl. Looking forward to seeing how it evolves!
